# Generated by Django 2.2.19 on 2024-02-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu_name',
            field=models.CharField(default='main_menu', max_length=100, verbose_name='Название_меню'),
        ),
    ]
